#服务的消费者配置文件
server:
  port: 9001
#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/ #注册到Eureka的地址
      #获取服务地址列表间隔时间，默认30s
    registry-fetch-interval-seconds: 10
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 #单位毫秒