server:
  port: 9002
spring:
  application:
    name: FEGIN-CONSUMER
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka #注册到Eureka的地址
TEST-PROVIDER:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 2000
    OkToRetryOnAllOperations: true
#参数配置来开启指定Fegin客户端的DEBUG日志
logging:
  level: 
    com.example.fegin.service.fegin.HelloService: debug