server:
  port: 9002
spring:
  application:
    name: FEIGN-CONSUMER
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka #注册到Eureka的地址
TEST-PROVIDER:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 2000
    OkToRetryOnAllOperations: true