server:
  port: 8889
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #路由id，可以任意
        - id: test-provider-route
          #代理的服务地址
          #uri: http://127.0.0.1:8001
          #lb表示从eureka中获取具体的服务
          uri: lb://TEST-PROVIDER
          #路由断言：可以匹配映射路径
          predicates:
#            - Path=/user/**
#            - Path=/**
            - Path=/api/user/**
          filters:
            #添加请求路径的前缀
#            - PrefixPath=/user
            #表示过滤1个路径，2表示两个路径。以此类推
              - StripPrefix=1
#              - MyParam=name
      #默认过滤器，对所有的路由都生效
      default-filters: 
        - AddResponseHeader=X-Response-Foo, Bar
      #Gateway跨域配置
      #跨域：在js请求地址中，如果访问的地址与当前服务器的域名、ip或者端口号不一致则称为跨域请求，如不解决则不能获取到对应地址的返回结果
      globalcors:
        cors-configurations: 
          '[/**]':
#            allowedOrigins: * #这种写法或者下面的都可以，*代表全部
            allowedOrigins:
              - "http://docs.spring.io"
            allowedMethods:
              - GET
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/
  instance:
    prefer-ip-address: true #使用IP，不使用Host
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
