#网关服务的配置文件
server:
  port: 9527
spring:
  application:
    name: ZUUL-SERVER #Zuul网关在Eureka的服务名称，随便取
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka     #Eureka的注册地址
  instance:
    prefer-ip-address: true
zuul:
  #禁用指定的过滤器
  AccessFilter:
    pre:
      disable: true
  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: TEST-PROVIDER
#    api-b:
#      path: /api-b/**
#      serviceId: FEGIN-CONSUMER
    provider:
      #没有提示，自己取名称，值为服务的名称。1、通过网关访问服务提供，请求地址为：127.0.0.1:9527/zuul-server/fegin-consumer/consumer-fegin
      serviceId: FEGIN-CONSUMER 
      #匹配指定的路径，资源匹配的路径才会拦截，转发。2、这时再次访问服务的提供者，请求地址变成：127.0.0.1:9527/test/consumer-fegin
      path: /test/**  
    #新增
    configProvider.serviceId: MICRO-SERVER-DEV  
    #新增
    configProvider.path: /config-provide/**  
  #忽略直接使用服务名   *忽略所有的服务
  ignored-services: "*"
  #统一给访问前缀。3、这时，访问服务的提供者，请求的地址为：127.0.0.1:9527/server/test/consumer-fegin
  prefix: /server 
  #默认情况下，zuul会过滤掉HTTP请求头信息中的一些敏感信息，防止它们被传递到下游的外部服务器，
  #这样的话使用了Spring Security、Shiro等安全框架构建的Web应用将无法实现登录和鉴权。
  sensitive-headers: 