#负载均衡 服务调用者配置文件
server:
  port: 9003
eureka:
  client:
    register-with-eureka: false  #不注册到Eureka,不在注册中心显示
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
#负载均衡配置
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true #该参数用来开启重试机制，它默认是关闭的